FROM jenkins/jenkins:jdk11
USER root
RUN apt-get update && apt-get install -y lsb-release
RUN curl -fsSLo /usr/share/keyrings/docker-archive-keyring.asc https://download.docker.com/linux/debian/gpg
RUN echo "deb [arch=$(dpkg --print-architecture) \
    signed-by=/usr/share/keyrings/docker-archive-keyring.asc] \
    https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
RUN apt-get update && apt-get install -y docker-ce-cli
USER jenkins
RUN jenkins-plugin-cli --plugins "docker-workflow"

# FROM maven:3-openjdk-17-slim AS base
# WORKDIR /app
# COPY .mvn/ .mvn
# COPY pom.xml ./
# RUN mvn dependency:resolve
# COPY src ./src

# FROM base as build
# RUN mvn package

# FROM openjdk:17-jdk-slim as production
# COPY --from=build /app/target/output.jar /output.jar
# CMD ["java", "-jar", "/output.jar"]


